### PR TITLE
SEIFA functions, Code of Conduct and Contributions

### PR DESCRIPTION
**Pull request by mrjoh3**
The code of conduct has just been copied from the runapp website. I had a go at the CONTRIBUTIONS document and loosly based it on the pkgdown version. You will wan to check it and ensure it meets you intent. Both of these are in the .github file and automatically link to the pkgdown website via the right side bar.

The seifa functions are working and have basic tests. They still need work but I wanted to check they are going in the right direction. We might also want to come up with a function naming convention to be consistent.

At some stage It might also be worth trying to add devtools::document() and pkgdown::build_site() to the github actions. This way we only push changes to source files and avoid merge conflicts with .Rd and .html files. I am sure this is possible but have not really used github actions before

### CODE REVIEW

**Comment by wfmackey** [comment]
Nice! CONTRIBUTIONS page looks good (ideally I'd like to expand it out to be more of an educational resource for newcomers -- but it works well for now). 

I've opened issues for adding to Github Actions (good idea, I can do this); and a broader discussion about naming conventions. Given the `experimental` nature of the package, I think this PR can go ahead without resolving either.

I added some imports to pass local checks, but it is now failing tests at `sa1 spreadsheet can be parsed`.

**Review by wfmackey — CHANGES_REQUESTED** [review]
Fix test failing: `ERROR (test-lga_seifa.R:30:3): sa1 spreadsheet can be parsed`

**Comment by mrjoh3** [comment]
looks like it failed because I used the here package to access a file in inst/extdata. So the test works in the project context on my pc but not in the test context gitlab action check. I have switched to system.file() to retrieve the correct filepath.

**Review by wfmackey — APPROVED** [review]
Great stuff

**Comment by wfmackey** [comment]
@mrjoh3 feel free to merge if you're happy with it!

**Comment by mrjoh3** [comment]
@wfmackey I don't think I have write access, so can't merge the request

**Comment by wfmackey** [comment]
@mrjoh3 should be fixed now

**Pull request merged**
